//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionStoreArzuTorg
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConstructionStoreEntities : DbContext
    {
        public ConstructionStoreEntities()
            : base("name=ConstructionStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LogsInfo> LogsInfo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ВозвратТовара> ВозвратТовара { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<Единицы_измерения> Единицы_измерения { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<ЗаказанныеТовары> ЗаказанныеТовары { get; set; }
        public virtual DbSet<Категория> Категория { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Поставки> Поставки { get; set; }
        public virtual DbSet<ПоставленныеТовары> ПоставленныеТовары { get; set; }
        public virtual DbSet<Поставщик> Поставщик { get; set; }
        public virtual DbSet<РазмерыТовара> РазмерыТовара { get; set; }
        public virtual DbSet<Резервация> Резервация { get; set; }
        public virtual DbSet<РезервацияТоваров> РезервацияТоваров { get; set; }
        public virtual DbSet<Сезонность> Сезонность { get; set; }
        public virtual DbSet<Склад> Склад { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<СотрудникПользователь> СотрудникПользователь { get; set; }
        public virtual DbSet<Статус> Статус { get; set; }
        public virtual DbSet<Товар> Товар { get; set; }
    }
}
