//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionStoreArzuTorg
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказанныеТовары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ЗаказанныеТовары()
        {
            this.ВозвратТовара = new HashSet<ВозвратТовара>();
        }
    
        public int ID { get; set; }
        public int Товар { get; set; }
        public int Количество { get; set; }
        public int Заказ { get; set; }
        public Nullable<decimal> Сумма { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ВозвратТовара> ВозвратТовара { get; set; }
        public virtual Заказ Заказ1 { get; set; }
        public virtual Товар Товар1 { get; set; }
    }
}
