//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionStoreArzuTorg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Поставки()
        {
            this.ПоставленныеТовары = new HashSet<ПоставленныеТовары>();
        }
    
        public int ID { get; set; }
        public System.DateTime Дата { get; set; }
        public int Сотрудник { get; set; }
        public int Поставщик { get; set; }
        public decimal Сумма { get; set; }
    
        public virtual Поставщик Поставщик1 { get; set; }
        public virtual Сотрудник Сотрудник1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПоставленныеТовары> ПоставленныеТовары { get; set; }
    }
}
