//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionStoreArzuTorg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставщик
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Поставщик()
        {
            this.Поставки = new HashSet<Поставки>();
        }
    
        public int ID_Поставщика { get; set; }
        public string Наименование { get; set; }
        public string Расчётный_счёт { get; set; }
        public string Учётный_номер_плательщика { get; set; }
        public string Название_банка { get; set; }
        public string Код_банка { get; set; }
        public string Адрес { get; set; }
        public string ФИО { get; set; }
        public string Телефон { get; set; }
        public string Должность { get; set; }
        public string Почта { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Поставки> Поставки { get; set; }
    }
}
