//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionStoreArzuTorg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Резервация
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Резервация()
        {
            this.РезервацияТоваров = new HashSet<РезервацияТоваров>();
        }
    
        public int ID { get; set; }
        public System.DateTime Дата { get; set; }
        public int Клиент { get; set; }
        public decimal Цена { get; set; }
        public int Статус { get; set; }
    
        public virtual Клиент Клиент1 { get; set; }
        public virtual Статус Статус1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РезервацияТоваров> РезервацияТоваров { get; set; }
    }
}
