//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionStoreArzuTorg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товар()
        {
            this.ЗаказанныеТовары = new HashSet<ЗаказанныеТовары>();
            this.ПоставленныеТовары = new HashSet<ПоставленныеТовары>();
            this.РезервацияТоваров = new HashSet<РезервацияТоваров>();
            this.Склад = new HashSet<Склад>();
        }
    
        public int ID_Товара { get; set; }
        public string Название { get; set; }
        public int ID_Категории { get; set; }
        public int ID_Размеров { get; set; }
        public int ID_Единицы_измерения { get; set; }
        public decimal Стоимость { get; set; }
        public int Сезонность { get; set; }
        public Nullable<decimal> Стоимость_со_скидкой { get; set; }
        public Nullable<int> Серийный_номер { get; set; }
        public string Гарантия { get; set; }
    
        public virtual Единицы_измерения Единицы_измерения { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗаказанныеТовары> ЗаказанныеТовары { get; set; }
        public virtual Категория Категория { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПоставленныеТовары> ПоставленныеТовары { get; set; }
        public virtual РазмерыТовара РазмерыТовара { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РезервацияТоваров> РезервацияТоваров { get; set; }
        public virtual Сезонность Сезонность1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Склад> Склад { get; set; }
    }
}
