//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElectivesEntities : DbContext
    {
        public ElectivesEntities()
            : base("name=ElectivesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<Преподаватель> Преподаватель { get; set; }
        public virtual DbSet<Справочник_Факультативов> Справочник_Факультативов { get; set; }
        public virtual DbSet<Студенты> Студенты { get; set; }
        public virtual DbSet<Учебный_план> Учебный_план { get; set; }
        public virtual DbSet<Факультативов_в_семестре> Факультативов_в_семестре { get; set; }
    }
}
