//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Справочник_Факультативов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Справочник_Факультативов()
        {
            this.Факультативов_в_семестре = new HashSet<Факультативов_в_семестре>();
        }
    
        public int Код_Справочника { get; set; }
        public string Название { get; set; }
        public Nullable<int> Часы { get; set; }
        public int Объём_лекций { get; set; }
        public int Объём_практик { get; set; }
        public int Объём_лабораторных_работ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        protected virtual ICollection<Факультативов_в_семестре> Факультативов_в_семестре { get; set; }
    }
}
