//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Учебный_план
    {
        public int ID_Учебного_плана { get; set; }
        public int Оценка { get; set; }
        public System.DateTime Дата { get; set; }
        public int Курс { get; set; }
        public int Код_факультатива { get; set; }
        public int Код_студента { get; set; }
    
        protected virtual Студенты Студенты { get; set; }
        protected virtual Факультативов_в_семестре Факультативов_в_семестре { get; set; }
    }
}
