//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Факультативов_в_семестре
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Факультативов_в_семестре()
        {
            this.Учебный_план = new HashSet<Учебный_план>();
        }
    
        public int Код_Факультатива { get; set; }
        public Nullable<int> Количество_часов { get; set; }
        public int ЛР { get; set; }
        public int Практика { get; set; }
        public int Номер_семестра { get; set; }
        public int Код_преподавателя { get; set; }
        public int Код_справочника { get; set; }
    
        protected virtual Преподаватель Преподаватель { get; set; }
        protected virtual Справочник_Факультативов Справочник_Факультативов { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        protected virtual ICollection<Учебный_план> Учебный_план { get; set; }
    }
}
